/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 *
 * Detailed information about configuring a multi-project build in Gradle can be found
 * in the user manual at https://docs.gradle.org/7.6/userguide/multi_project_builds.html
 */

rootProject.name = "the-christmas-challenge"
include(":reindeer")
project(":reindeer").projectDir = file("software/reindeer")

include(":infrastructure")
project(":infrastructure").projectDir = file("infrastructure")

